### ISSUE TITLE
slice.py error

### ISSUE THREAD

**Issue by sorui-qin** [undeadpixel/reinvent-scaffold-decorator#10]
Hi, I tried to train the model with my own selected molecules downloaded from ChEMBL.
There were about 4k molecules and can be sliced with RECAP rules.
But when I running slice.py as README, the program fed back with error as follows:
[Stage 9:============================>                         (268 + 56) / 500]22/02/22 22:44:51 ERROR Executor: Exception in task 285.0 in stage 9.0 (TID 411)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/miniconda3/envs/reinvent-scaffold-decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/opt/ohpc/pub/apps/miniconda3/envs/reinvent-scaffold-decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/ohpc/pub/apps/miniconda3/envs/reinvent-scaffold-decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 400, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/opt/ohpc/pub/apps/miniconda3/envs/reinvent-scaffold-decorator/lib/python3.6/site-packages/pyspark/rdd.py", line 1354, in takeUpToNumLeft
    yield next(iterator)
  File "/opt/ohpc/pub/apps/miniconda3/envs/reinvent-scaffold-decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "./slice_db.py", line 37, in _enumerate
    for sliced_mol in enumerator.enumerate(mol, cuts=cuts):
  File "/home/ljp/qinrui/reinvent-scaffold-decorator-master/utils/scaffold.py", line 147, in enumerate
    sliced_mols.add(SlicedMol(fragments[0], [fragments[1]]))
  File "/home/ljp/qinrui/reinvent-scaffold-decorator-master/utils/scaffold.py", line 29, in __init__
    self._normalize()
  File "/home/ljp/qinrui/reinvent-scaffold-decorator-master/utils/scaffold.py", line 61, in _normalize
    self.decorations = {curr2can[num]: dec for num, dec in self.decorations.items()}
  File "/home/ljp/qinrui/reinvent-scaffold-decorator-master/utils/scaffold.py", line 61, in <dictcomp>
    self.decorations = {curr2can[num]: dec for num, dec in self.decorations.items()}
KeyError: 0

I tried to fix my training set for many times but it still didn't work.
I'm wondering why cause it happened. Thanks.

**Comment by sorui-qin** [comment]
I read the SI again and I found what's happened to my training set.
The issue will be closed :)
