### ISSUE TITLE
slice_db.py runs slow chembl dataset

### ISSUE THREAD

**Issue by xinyuwang1209** [undeadpixel/reinvent-scaffold-decorator#6]
I tried to run `slice_db.py`for chembl set:

`$ ./slice_db.py -i training_sets/chembl.recap.smi.gz -u chembl_decorator-excape.chembl.hr.smi -s hr -f conditions.json.example`

However, the progress is very slow and I am not sure how long it will take to finish. Is there any way to speed up the progress? Thanks.

**Comment by sorui-qin** [comment]
I had the same issue, but I didn't use chembl set but my own dataset.

After I replace the old dataset and run `slice_db.py` for my own dataset, the progress feedback in shell always stuck in this status as follow:

`[Stage 3:=====================================================>(999 + 1) / 1000]`

I have checked my data format but couldn't find any obvious mistake, so I want to ask is there any solution with the issue?
Sincerely thanks.

**Comment by undeadpixel** [comment]
Hi,

Sorry for the long delay in answering. I think that the problem you are having is that you use a gigantic dataset and you don't have either enough CPUs or memory. I found it very useful to dimension the amount of data that you want to slice. Start with a small set, and then see how big they get. For example: if there are not a lot of molecules but these are very big, there are going to be a lot of possible slicings and the process can get unexpectedly slow. Then you try with some molecules more and see how it gets. I was able to find the size of the subset of chembl by doing it like this. 

Cheers,

Josep

**Comment by adriacb** [comment]
Having this problem executing the same command:

To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[Stage 0:>                                                          (0 + 1) / 1]22/06/16 08:10:37 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 875, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'utils'



Any idea?
Thanks!

**Comment by sorui-qin** [comment]
> Having this problem executing the same command:
> 
> To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel). [Stage 0:> (0 + 1) / 1]22/06/16 08:10:37 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1) org.apache.spark.api.python.PythonException: Traceback (most recent call last): File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main func, profiler, deserializer, serializer = read_command(pickleSer, infile) File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command command = serializer._read_with_length(file) File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length return self.loads(obj) File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads return pickle.loads(obj, encoding=encoding) File "/home/.../.conda/envs/RSD/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 875, in subimport **import**(name) ModuleNotFoundError: No module named 'utils'
> 
> Any idea? Thanks!

Hi,

I'm wondering if there might be two problems in your report.

First, the feedbacks all seem to be attached to Pyspark, so please check whether this module is installed correctly and successfully.

And another possible problem is showing as `ModuleNotFoundError: No module named 'utils'` 

`./utils` is an important subfolder for running all codes. Please make sure that the `./utils` subfolder stays with the other file in the main folder. 

Hope those above could help you.

Qin.

**Comment by undeadpixel** [comment]
Hi @adriacb & @sorui-qin,

I think that @sorui-qin has said exactly what I wanted to say 😄. You should run the scripts from the same folder as the code and you should also be careful that pyspark doesn't work with the latest java versions (< 11, but I would recommend to use 8).

Please tell me if you still have any remaining issues and I'll try to help you as much as I can.

Thanks!
