### ISSUE TITLE
pyspark ConnectionResetError

### ISSUE THREAD

**Issue by ClinuxMDL** [undeadpixel/reinvent-scaffold-decorator#8]
Hi,

I had a problem when I ran a large sampling. 

```
activate decorator 

spark-submit --driver-memory=32g --executor-cores=8 --executor-memory=100G sample_scaffolds.py -m trained_models/chembl.ms.recap.100.model -i data/12_9_scaffold.smi -o data/12_9_sample.smi --of=csv -r 8 -n 16 -b 8192 -d multi
```
The output log:

...
Sampling:  93%|#########2| 135536/146173 [16:53<01:19, 133.78it/s]
Traceback (most recent call last):
  File "/gpfs1/iip_pkuhpc/iip_test/zhangjianhang/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 288, in <module>
    main()
  File "/gpfs1/iip_pkuhpc/iip_test/zhangjianhang/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 277, in main
    results_df = sample_scaffolds.run(input_scaffolds)
  File "/gpfs1/iip_pkuhpc/iip_test/zhangjianhang/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 97, in run
    self._sample_and_write_scaffolds_to_disk(scaffolds, scaffolds_df.count())
  File "/gpfs1/iip_pkuhpc/iip_test/zhangjianhang/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 142, in _sample_and_write_scaffolds_to_disk
    for (idx, scaffold) in ul.progress_bar(scaffolds, total=total_scaffolds, desc="Sampling"):
  File "/home/iip_pkuhpc/gpfs1/iip_test/zhangjianhang/miniconda3/envs/decorator/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/iip_pkuhpc/gpfs1/iip_test/zhangjianhang/miniconda3/envs/decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 148, in load_stream
  File "/home/iip_pkuhpc/gpfs1/iip_test/zhangjianhang/miniconda3/envs/decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 170, in _read_with_length
  File "/home/iip_pkuhpc/gpfs1/iip_test/zhangjianhang/miniconda3/envs/decorator/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

Thanks~

**Comment by undeadpixel** [comment]
Hi!

Thanks for trying the software. Generally these errors happen when there is not enough memory allocated.

I see that you use executor memory and executor cores: this doesn't work in spark local mode. To set the memory in local mode you have to use `--driver-memory=XXg` and to set the number of cores you need to set the `--master local[X]`, where `X=num_cores`. Could you try to sample smaller amounts (by lowering `-r`, `-n` and `-b`) and see where do you hit the limit?

Cheers,

Josep
