### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by freelancercjdscs** [undeadpixel/reinvent-scaffold-decorator#9]
I tried sampling scaffolds many times, but always failed with the following error:

18:31:22: actions._log +32: INFO     Starting iteration #0.
18:31:27: actions._log +32: INFO     Generated 38205 randomized SMILES from 24272 scaffolds.
Sampling: 100%|##########| 38205/38205 [00:01<00:00, 25083.03it/s]
18:36:01: actions._log +32: INFO     Sampled 38205 scaffolds.
18:37:15: actions._log +32: INFO     Joined 38205 -> 607510 (valid) -> 161944 unique sampled scaffolds
18:37:17: actions._log +32: INFO     Obtained 146173 scaffolds for next iteration.
18:37:19: actions._log +32: INFO     Starting iteration #1.
18:37:28: actions._log +32: INFO     Generated 146173 randomized SMILES from 146173 scaffolds.
Sampling:  93%|#########2| 135536/146173 [16:53<01:19, 133.78it/s]
Traceback (most recent call last):
  File "/gpfs1/user/test1/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 288, in <module>
    main()
  File "/gpfs1/user/test1/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 277, in main
    results_df = sample_scaffolds.run(input_scaffolds)
  File "/gpfs1/user/test1/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 97, in run
    self._sample_and_write_scaffolds_to_disk(scaffolds, scaffolds_df.count())
  File "/gpfs1/user/test1/reinvent-scaffold-decorator-master/sample_scaffolds.py", line 142, in _sample_and_write_scaffolds_to_disk
    for (idx, scaffold) in ul.progress_bar(scaffolds, total=total_scaffolds, desc="Sampling"):
  File "/home/user/gpfs1/test1/miniconda3/envs/decorator/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/user/gpfs1/test1/miniconda3/envs/decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 148, in load_stream
  File "/home/user/gpfs1/test1/miniconda3/envs/decorator/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 170, in _read_with_length
  File "/home/user/gpfs1/test1/miniconda3/envs/decorator/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

All calculations were carried out on a single node within a cluster, what is the cause of this error?  Thanks.

**Comment by undeadpixel** [comment]
Hi!

Thanks for trying it out! I think that the problem you are having is that the dataset you are trying to process is extremely large, and it has an out of memory error. Generally, the `Connection reset by peer` error appears when the Spark process is killed by the cluster scheduler because of a too high memory usage.

Could you try increasing memory and also increasing the memory allocation to Spark? Also, generally spark lies: when you allocate memory using `--spark-driver-memory=32g`, you should have at least `40g` memory in your scheduled task, because java tends to use more memory than the one that you set up with.

Hope it helps,

Josep
